langage: cpp

addons:
 sonarcloud: true
 apt:
  sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:mhier/libboost-latest'
  packages:
    - g++-7
    - cmake
    - cmake-data

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

jobs:
  include:
  - stage: Unit Tests
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make
      - cd ..
      - ./client_tests
      - ./server_tests
  - stage: Unit Tests & Sonar
    if: (NOT type IN (pull_request)) AND (branch = master)
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make
      - cd ..
      - ./client_tests
      - ./server_tests
      # - gcovr -r . -x --object-directory=. > report.xml
      # - sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.login=$SONAR_TOKEN -X

env:
 global:
 - secure: b4cdbad4a6e72c26069bba3362c5bcce31105f82

 - SONAR_HOST_URL=http://91.121.150.220:9000
